const newLoaded = [
  {
    Categoria: "Actualidad",
    Destacado: false,
    Titulo: `Por qué el riesgo país cayó casi 50% y cerró en 1.104 puntos`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/10/tlam-859975-195611.jpg`,
    DetalleCorto:
      "El riesgo país cayó hoy casi un 50% y cerró en 1.104 puntos básicos como consecuencia de la reconfiguración del índice medido por el banco de inversión J.P. Morgan, que incorporó los bonos nuevos del canje de la deuda.",
  },
  {
    Categoria: "Actualidad",
    Destacado: false,
    Titulo: `Tucumán volverá a contar con servicio de ómnibus, tras un paro de 16 días`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/07/28/paro-de-colectivos-miles-tucumanos-tuvieron-inconvenientes-para-asistir-lugares-trabajo-853576-220624.jpg`,
    DetalleCorto:
      "Dirigentes de la delegación local de la UTA anunciaron que mañana las empresas depositarán lo adeudado, por lo que se levanta la medida de fuerza a partir de las 0 horas de mañana.",
  },
  {
    Categoria: "Actualidad",
    Destacado: false,
    Titulo: `Tucumán tuvo el peor día desde que comenzó la pandemia: sumó 480 casos de covid-19`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/10/la-gaceta-foto-de-anala-jaramillo-859955-185429.jpg`,
    DetalleCorto:
      "Tucumán sumó 480 nuevos contagios de covid-19 en las ultimas 24 horas, la cifra más alta desde que comenzó la pandemia, y llegó a los 5.820 casos confirmados, informó el Ministerio de Salud de la Provincia.",
  },
  {
    Categoria: "Espectaculos",
    Destacado: false,
    Titulo: `El Incaa abre convocatoria para largometrajes, para animación y para series de formato corto`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/10/convocatoria-concurso-incaa-esta-destinado-productores-directores-guionistas-todas-regiones-pais-859998-215021.jpg`,
    DetalleCorto: "El “Concurso Federal de Desarrollo de Proyectos Inéditos” está destinado a productores, directores y guionistas de todo el país, que podrán presentar propuestas hasta el viernes 9 del mes que viene.",
  },
  {
    Categoria: "Espectaculos",
    Destacado: false,
    Titulo: `Murió Diana Rigg, la emblemática actriz de “Juego de tronos” y “Los vengadores” `,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/10/murio-diana-rigg-emblematica-actriz-juego-tronos-vengadores-859903-124251.jpg`,
    DetalleCorto: "Aunque se hizo mundialmente famosa por sus papeles en esas series, Rigg tuvo una brillante con algunas de las más ilustres compañías de teatro del Reino Unido.",
  },
  {
    Categoria: "Espectaculos",
    Destacado: false,
    Titulo: `Ciclo virtual: la UTN rinde tributo a los “Hacedores del Tucumán” cultural`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/10/859785_202009091904450000001.jpg`,
    DetalleCorto: "Chichí Costello, Mercedes Sosa, Pato Gentilini y Chivo Valladares serán los homenajeados este año.",
  },
  {
    Categoria: "Tecnologia",
    Destacado: false,
    Titulo: `Android 11 Go: Google anuncia su nueva versión del sistema operativo para teléfonos de gama de entrada`,
    Imagen: `https://bucket1.glanacion.com/anexos/fotos/11/3390811w1033.jpg`,
    DetalleCorto: "Android 11 Go promete actualizar los teléfonos de gama de entrada con la última versión del sistema operativo de Google",
  },
  {
    Categoria: "Tecnologia",
    Destacado: false,
    Titulo: `¿Se frenó la innovación en smartphones? La visión desde el corazón de la industria en China`,
    Imagen: `https://bucket3.glanacion.com/anexos/fotos/09/3390809w1033.jpg`,
    DetalleCorto: "Li Bingzhong, más conocido como Sky Li, nació en 1975 y se graduó en la Universidad de Aeronáutica y Astronáutica de Nanjing. Fundó Realme en 2018 después de ser vicepresidente de Oppo durante varios años",
  },
  {
    Categoria: "Tecnologia",
    Destacado: false,
    Titulo: `Zoom ahora ofrece la autenticación en dos factores para todas las cuentas`,
    Imagen: `https://bucket3.glanacion.com/anexos/fotos/46/3390746w1033.jpg`,
    DetalleCorto: "Zoom comenzó a ofrecer el servicio de validación de identidad en dos factores, una modalidad que busca reforzar la seguridad en la plataforma de videollamadas",
  },
  {
    Categoria: "Deportes",
    Destacado: false,
    Titulo: `Gallardo podría quedarse sin una pieza clave para la Libertadores`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/07/02/849922_202007011945120000001.jpg`,
    DetalleCorto: "River recibió una oferta desde España por Lucas Martínez Quarta.",
  },
  {
    Categoria: "Deportes",
    Destacado: false,
    Titulo: `Barcelona vuelve a la carga por Lautaro Martínez`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/11/859990_202009102055160000001.jpg`,
    DetalleCorto: "El club catalán está dispuesto a pagar 65 millones de euros y ceder algún jugador a Inter",
  },
  {
    Categoria: "Deportes",
    Destacado: false,
    Titulo: `“Toda la gente, una cosa, una locura…”: Vignolo y lo vivido en la cancha de Atlético Tucumán`,
    Imagen: `https://www.eltucumano.com/fotos/cache/notas/2020/09/10/818x460_200910094001_49027.jpg`,
    DetalleCorto: "El periodista destacó al Monumental José Fierro como uno de los estadios más vibrantes del fútbol argentino. “Se movía”, contó.",
  },
  {
    Categoria: "Politica",
    Destacado: false,
    Titulo: `Liberaron a "El Presto", el influencer investigado por amenazas contra Cristina`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/11/twitter-elpresto2ok-860087-145058.jpeg`,
    DetalleCorto: "El joven había sido detenido ayer, tras resistirse a un allanamiento en su casa.",
  },
  {
    Categoria: "Politica",
    Destacado: false,
    Titulo: `La inseguridad se mantiene como el principal problema para los tucumanos`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/08/17/360x202_ayuda-se-consideraba-clave-esta-ley-lucha-contra-inseguridad-856465-215112.jpg`,
    DetalleCorto: "El último sondeo de opinión de la consultora Meraki reflejó que la inseguridad se mantuvo como el principal problema” para la población tucumana.",
  },
  {
    Categoria: "Politica",
    Destacado: false,
    Titulo: `El Presidente, a Rodríguez Larreta: "a alguno le duele renunciar a los privilegios"`,
    Imagen: `https://img.lagaceta.com.ar/fotos/notas/2020/09/04/apasionado-presidente-alberto-fernandez-dijo-encuentro-via-zoom-referentes-frente-todos-militantes-no-ve-hora-pase-pandemia-porque-859105-191750.jpg`,
    DetalleCorto: "Fernández defendió la quita de un punto de la coparticipación a la Ciudad de Buenos Aires, para transferirla al gobierno bonaerense.",
  },
  {
    Categoria: "Economia",
    Destacado: false,
    Titulo: `Coronavirus. Crisis en el turismo: la mitad de los hoteles podrían cerrar si se prolonga la parálisis`,
    Imagen: `https://bucket1.glanacion.com/anexos/fotos/70/3177770w1033.jpg`,
    DetalleCorto: "Según una asociación hotelera, ya han dejado de operar casi 4000 emprendimientos turísticos",
  },

  {
    Categoria: "Economia",
    Destacado: false,
    Titulo: `Naftas. Traban los despachos de combustible y advierten sobre posibles faltantes para el fin de semana`,
    Imagen: `https://bucket3.glanacion.com/anexos/fotos/58/3390658w1033.jpg`,
    DetalleCorto: "La Federación Argentina Sindical de Petróleo, Gas y Biocombustible frenó desde esta madrugada el despacho de combustible en la refinería de Bahía Blanca de Trafigura, la empresa petrolera que controla las estaciones de servicio de Puma Energy",
  },
  {
    Categoria: "Economia",
    Destacado: false,
    Titulo: `Créditos Procrear. Cómo acceder a la nueva línea que arranca mañana`,
    Imagen: `https://bucket1.glanacion.com/anexos/fotos/01/2691301w1033.jpg`,
    DetalleCorto: "El Ministerio de Desarrollo Territorial y Hábitat informó el tope de los montos a los que se podrá acceder",
  },
  {
    Categoria: "Salud",
    Destacado: false,
    Titulo: `Investigadores identifican una proteína clave para evitar la metástasis del cáncer de mama`,
    Imagen: `https://bucket1.glanacion.com/anexos/fotos/10/3389110w1033.jpg`,
    DetalleCorto: "Importante avance contra el cáncer de mama",
  },
  {
    Categoria: "Salud",
    Destacado: false,
    Titulo: `Vitamina D: cuáles son los alimentos que se pueden ingerir para obtenerla`,
    Imagen: `https://bucket2.glanacion.com/anexos/fotos/44/3258644w1033.jpg`,
    DetalleCorto: "Tomar sol, una de las formas más sencillas de absorber la vitamina D. Sin embargo, a partir del daño en la capa de ozono, los especialistas recomiendan optar por la suplementación",
  },
  {
    Categoria: "Salud",
    Destacado: false,
    Titulo: `Covid-19. "Una vacuna apresurada hará más mal que bien"`,
    Imagen: `https://bucket3.glanacion.com/anexos/fotos/49/3380249w1033.jpg`,
    DetalleCorto: "La Administración de Alimentación y Medicamentos de Estados Unidos (FDA, por sus siglas en inglés) adelantó que podría aprobar el uso de emergencia de una vacuna contra el coronavirus antes de que terminen los ensayos clínicos",
  },
  {
    Categoria: "Fotografia",
    Destacado: false,
    Titulo: `FOTOS | Algunos de los incidentes explosivos más recordados del deporte`,
    Imagen: `https://cnnespanol.cnn.com/wp-content/uploads/2020/09/sua%CC%81rez-muerde-e1599537733549.jpg?quality=100&strip=info&w=940&h=530&crop=1`,
    DetalleCorto: "Luis Suárez tiene una larga trayectoria de agresiones dentro de la cancha. En 2010, cuando jugaba en el Ajax, el futbolista uruguayo mordió al holandés Otman Bakkal. Tres años más tarde, estando en el Liverpool, mordió a Branislav Ivanovic. Y en el Mundial 2014 le tocó al italiano Giorgio Chiellini",
  },
  {
    Categoria: "Fotografia",
    Destacado: false,
    Titulo: `FOTOS | Algunos de los incidentes explosivos más recordados del deporte`,
    Imagen: `https://cnnespanol.cnn.com/wp-content/uploads/2020/09/Mike-Tyson.jpg?quality=100&strip=info&w=940&h=530&crop=1`,
    DetalleCorto: "Mike Tyson le mordió la oreja a Evander Holyfield durante una pelea por el título de pesos pesados en 1997. Enfrentó una suspensión de un año",
  },

  {
    Categoria: "Fotografia",
    Destacado: false,
    Titulo: `FOTOS | Las primeras imágenes del premio Mejor Fotógrafo de Vida Silvestre 2020`,
    Imagen: `https://cnnespanol.cnn.com/wp-content/uploads/2020/09/fotografo-vida-silvestre-2020-premios-Imagenes-a.jpg`,
    DetalleCorto: "Esta Imagen de un primate en peligro de extinción fue tomada por un niño de 13 años.",
  },
];

export default newLoaded;
